spring:
  application:
    name: pickcar-domain
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

# 민감하지 않은 공통 설정
custom:
  reservation:
    cool-down-minutes: 30
  driveHistory:
    maximum-inquiry-days: 30

logging:
  module-name: domain
  sensitive-field-rules:
    - path: "/api/v1/auth/login"
      fields: [ "email", "password" ]
    - path: "/api/v1/auth/login_after"
      fields: [ "email", "password" ]
    - path: "/api/v1/auth/sign-up"
      fields: [ "email", "password", "name", "phoneNumber" ]
    - path: "/api/v1/auth/users"
      fields: [ "email", "password", "name", "phoneNumber" ]
    - path: "/api/v1/auth/admins"
      fields: [ "email", "password", "name", "phoneNumber" ]
    - path: "/api/v1/auth/test"
      fields: [ "email", "password", "name", "phoneNumber" ]