mq:
  cycle:
    queue: cycle-queue
    exchange: exchange-cycle
    routing-key: cycle.key
  event:
    queue: event-queue
    exchange: exchange-event
    routing-key: event.key

spring:
  profiles:
    active: local
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 5
        multiplier: 2.0
    listener:
      simple:
        default-requeue-rejected: false # 실패 메시지 재큐 금지(무한 반복 방지)

custom:
  logging:
    moduleName: consumer
    sensitiveFieldRules:
      - path: "none"
        fields: ["none"]