web:
  cors:
    allowed-origins: "https://pickcar.online"

http:
  endpoint:
    domain: "https://domain.pickcar.online"

jwt:
  secret-key: "67UxlKsXLsb0shXLgTwSdyYRLkSg0hIpQA1ekoKVZQc="

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: false