#운영용
version: '3.8'

services:
  pickcar-ws:
    image: openjdk:21-jdk
    container_name: pickcar-ws
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "8000:8080"
    volumes:
      - /home/ubuntu/pickcar/emulator-0.0.1-SNAPSHOT.jar:/app/app.jar
      - /home/ubuntu/pickcar/logs:/app/logs
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    networks:
      - pickcar-net

  pickcar-pub:
    image: openjdk:21-jdk
    container_name: pickcar-pub
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/pickcar/producer-0.0.1-SNAPSHOT.jar:/app/app.jar
      - /home/ubuntu/pickcar/logs:/app/logs
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    networks:
      - pickcar-net

  pickcar-sub:
    image: openjdk:21-jdk
    container_name: pickcar-sub
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - /home/ubuntu/pickcar/consumer-0.0.1-SNAPSHOT.jar:/app/app.jar
      - /home/ubuntu/pickcar/logs:/app/logs
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    networks:
      - pickcar-net

  pickcar-domain:
    image: openjdk:21-jdk
    container_name: pickcar-domain
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "8082:8080"
    volumes:
      - /home/ubuntu/pickcar/domain-0.0.1-SNAPSHOT.jar:/app/app.jar
      - /home/ubuntu/pickcar/logs:/app/logs
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    networks:
      - pickcar-net

volumes:
  mysql-data:
    name: mysql-data

networks:
  pickcar-net:
    name: pickcar-net