#Build
FROM eclipse-temurin:21-jdk AS builder
WORKDIR /app

COPY . .

RUN chmod +x ./gradlew

RUN ./gradlew :domain:build -x test --no-daemon

#Runtime
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=builder /app/domain/build/libs/domain-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
