spring:
  thymeleaf:
    cache: false
    prefix: 'classpath:/templates/'
    suffix: '.html'
  profiles:
    active: local

custom:
  logging:
    moduleName: emulator
    sensitiveFieldRules:
      - path: "none"
        fields: ["none"]