# ?? ?? ??
LOG_PATH=/app/logs

# ???? ?? ?? prefix
AUTH_LOG_FILE_NAME=pickcar-auth
PICKCAR_LOG_FILE_NAME=pickcar
ERROR_LOG_FILE_NAME=pickcar-error

# ?? ?? ?? ??
CONSOLE_LOG_PATTERN_COLOR=[%X{traceId}:%X{spanId}] %d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight([%-3level]) %cyan(%logger{10}) - %msg%n

# ?? ??? rolling ??
MAX_FILE_SIZE=30MB
TOTAL_SIZE_CAP=500MB
MAX_HISTORY=30