mq:
  cycle:
    exchange: exchange-cycle
    routing-key: cycle.key
  event:
    exchange: exchange-event
    routing-key: event.key

spring:
  thymeleaf:
    cache: false
    prefix: 'classpath:/templates/'
    suffix: '.html'

  profiles:
    active: local

mq:
  cycle:
    exchange: exchange-cycle
    routing-key: cycle.key
  event:
    exchange: exchange-event
    routing-key: event.key

custom:
  logging:
    moduleName: producer
    sensitiveFieldRules:
      - path: "none"
        fields: ["none"]
